### ISSUE TITLE
`Verification of X took Nms` repeats very slowly for EVERYTHING...

### ISSUE THREAD

**Issue by gefilte** [tmurakami/dexopener#2] opened 2017-05-24 21:02 UTC
does this for my classes, library classes, almost everything. 
e.g.:
```
05-24 12:43:22.852 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.buffer(int, int) took 147.824ms
05-24 12:43:22.992 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.buffer(int, int, java.util.concurrent.Callable) took 139.386ms
05-24 12:43:23.132 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.buffer(long, long, java.util.concurrent.TimeUnit, io.reactivex.Scheduler, java.util.concurrent.Callable) took 140.788ms
05-24 12:43:23.272 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.buffer(io.reactivex.ObservableSource, io.reactivex.functions.Function, java.util.concurrent.Callable) took 137.164ms
05-24 12:43:23.412 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.buffer(io.reactivex.ObservableSource, java.util.concurrent.Callable) took 140.923ms
05-24 12:43:23.552 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.buffer(java.util.concurrent.Callable, java.util.concurrent.Callable) took 141.834ms
05-24 12:43:23.702 W/art: Verification of io.reactivex.Observable io.reactivex.Observable.cache() took 148.045ms
```

Anyway, this whole thing doesn't start until the test starts... in my case it's an Activity test so eventually the rule times out the activity launch at 45 seconds and so we fail.

Running a single instrumentation test on a Marshmallow device using AndroidJUnit4. My app is MultiDex, so here's my test runner:

```
public class MultiDexJUnitTestRunner extends AndroidJUnitRunner {
    @Override
    public void onCreate(Bundle arguments) {
        MultiDex.install(getTargetContext());
        super.onCreate(arguments);
    }

    @Override
    public Application newApplication(ClassLoader cl, String className, Context context)
            throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        DexOpener.install(this);
        return super.newApplication(cl, className, context);
    }
}
```

Though the same symptom happened even if I comment out the MultiDex stuff, so that doesn't seem to be the reason...

**Comment by tmurakami** [comment] 2017-05-25 04:54
Thank you for reporting!
Could you share your reproducible project?

**Comment by gefilte** [comment] 2017-05-30 17:23
I don't think so, would take too long to redact. Any ideas on what settings I might have that would effect this?

**Comment by tmurakami** [comment] 2017-05-30 17:54
Recently we have released a new version 0.9.7.
We fixed some bugs and improved the performance.
Could you please try this version?

Also, if you specify a package you want to mock like the following, performance may be improved.
```java
public class YourAndroidJUnitRunner extends AndroidJUnitRunner {

    @Override
    public Application newApplication(ClassLoader cl, String className, Context context) 
            throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        DexOpener.builder(context)
                .openIf(name -> name.startsWith("package.you.want.to.mock."))
                .build()
                .installTo(cl);
        return super.newApplication(cl, className, context);
    }

}
```

And enabling code shrinking may be effective.
https://developer.android.com/studio/build/shrink-code.html#gradle-shrinker

**Comment by gefilte** [comment] 2017-05-30 20:38
This worked like a charm. Didn't need the shrinking business either, just updating to the latest and filtering per your example code was all that was needed. Thanks so much! 
Now to remove all those `// FIXME` comments... :)

**Comment by tmurakami** [comment] 2017-06-01 17:07
Since the problem seems to be solved, now I will close this issue.

**Closed by tmurakami** 2017-06-01 17:07 UTC
